--GUEST
INSERT INTO GUEST (GUESTNAME, COMMENT) VALUES ('Anton','12345');
INSERT INTO GUEST (GUESTNAME, COMMENT) VALUES ('Andrey','54321');
INSERT INTO GUEST (GUESTNAME, COMMENT) VALUES ('Son','Hi');



